#!/bin/bash


retval=0

echo 'creating antlr files...'
cd antlr
antlr4 -Dlanguage=Python3 SwumLexer.g4 SwumParser.g4 -visitor
cd ..
echo 'running phrases layer...'
python3 SwumPhrases.py $1 $2
if [ $? -eq 0 ]
then
    echo 'Success!'
else
    retval=$?
    echo "Failed with exit code ${retval}"
    rm $2 # delete output file
fi
echo 'deleting antlr files...'
cd antlr
rm -r __pycache__ SwumLexer.interp SwumLexer.py SwumLexer.tokens SwumParser.interp SwumParser.py SwumParser.tokens SwumParserListener.py SwumParserVisitor.py
cd ..

return $retval
